packages:
  - .
  - test/*
  - '!telemetry-worker'

onlyBuiltDependencies:
  - '@ast-grep/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

allowBuilds:
  "@ast-grep/cli": true
  esbuild: true
  sharp: true
