packages:
  - .
  - test/*
  - '!telemetry-worker'

overrides:
  '@lezer/common': ^1.5.0

onlyBuiltDependencies:
  - '@ast-grep/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

allowBuilds:
  "@ast-grep/cli": true
  esbuild: true
  sharp: true
