use tauri_specta::{collect_commands, Builder};

/// Export TypeScript bindings to the frontend (debug mode only)
#[cfg(debug_assertions)]
pub fn export_bindings() {
    let builder = generate_bindings();
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n/* eslint-disable */\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

pub fn generate_bindings() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // menu.rs commands
        crate::commands::menu::update_format_menu_state,
        // files.rs commands
        crate::commands::files::read_file,
        crate::commands::files::write_file,
        crate::commands::files::create_file,
        crate::commands::files::delete_file,
        crate::commands::files::rename_file,
        crate::commands::files::copy_file_to_assets,
        crate::commands::files::copy_file_to_assets_with_override,
        crate::commands::files::parse_markdown_content,
        crate::commands::files::update_frontmatter,
        crate::commands::files::save_markdown_content,
        crate::commands::files::save_recovery_data,
        crate::commands::files::save_crash_report,
        crate::commands::files::get_app_data_dir,
        crate::commands::files::write_app_data_file,
        crate::commands::files::read_app_data_file,
        crate::commands::files::read_file_content,
        crate::commands::files::write_file_content,
        crate::commands::files::create_directory,
        crate::commands::files::is_path_in_project,
        crate::commands::files::get_relative_path,
        crate::commands::files::resolve_image_path,
        // project.rs commands
        crate::commands::project::select_project_folder,
        crate::commands::project::scan_project,
        crate::commands::project::scan_project_with_content_dir,
        crate::commands::project::resolve_file_entry,
        crate::commands::project::scan_collection_files,
        crate::commands::project::load_file_based_collection,
        crate::commands::project::read_json_schema,
        crate::commands::project::scan_directory,
        crate::commands::project::count_collection_files_recursive,
        crate::commands::project::scan_collection_files_recursive,
        // watcher.rs commands
        crate::commands::watcher::start_watching_project,
        crate::commands::watcher::start_watching_project_with_content_dir,
        crate::commands::watcher::stop_watching_project,
        // preferences.rs commands
        crate::commands::preferences::open_preferences_folder,
        crate::commands::preferences::reset_all_preferences,
        // diagnostics.rs commands
        crate::commands::diagnostics::get_app_version,
        crate::commands::diagnostics::get_platform_info,
        crate::commands::diagnostics::get_app_info,
        // ide.rs commands
        crate::commands::ide::open_path_in_ide,
        // image_handler.rs commands
        crate::commands::image_handler::run_image_drop_command,
        // mdx_components.rs commands
        crate::commands::mdx_components::scan_mdx_components,
        // clipboard.rs commands
        crate::commands::clipboard::copy_text_to_clipboard,
        // updater.rs commands
        crate::commands::updater::fetch_release_notes,
        // fonts.rs commands
        crate::commands::fonts::get_linux_ui_font,
    ])
}
